server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, OK

      routes:
        # ==== API del Swipe Service ====
        - id: swipe-service.yml
          uri: lb://SWIPE-SERVICE
          predicates:
            - Path=/swipe-service.yml/**
          filters:
            - StripPrefix=1

        # ==== OpenAPI/Swagger del SwipeService (proxy) ====
        - id: swipe-service.yml-openapi
          uri: lb://SWIPE-SERVICE
          predicates:
            - Path=/swipe-service.yml/v3/api-docs/**, /swipe-service.yml/swagger-ui.html, /swipe-service.yml/swagger-ui/**, /swipe-service.yml/webjars/**, /swipe-service.yml/swagger-resources/**
          filters:
            - StripPrefix=1

        # ==== API del Config MS ====
        - id: confg-ms
          uri: lb://CONFG-MS
          predicates:
            - Path=/confg-ms/**
          filters:
            - StripPrefix=1

        # ==== OpenAPI/Swagger del Config MS (proxy) ====
        - id: confg-ms-openapi
          uri: lb://CONFG-MS
          predicates:
            - Path=/confg-ms/v3/api-docs/**, /confg-ms/swagger-ui.html, /confg-ms/swagger-ui/**, /confg-ms/webjars/**, /confg-ms/swagger-resources/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8762/eureka   # <--- CAMBIO para Docker

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: SwipeService
        url: /swipe-service.yml/v3/api-docs
      - name: ConfigMS
        url: /confg-ms/v3/api-docs
    disable-swagger-default-url: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,httpexchanges
  endpoint:
    health:
      show-details: always
